### ISSUE TITLE
Error on using Einstein for Developers extension

### ISSUE THREAD

**Issue by Salesforcetestuser** [forcedotcom/Einstein-GPT-for-Developers#48] opened 2024-02-29 14:21 UTC
### Summary
While clicking on the "ask" tin the "Einstein for developers" extension in VScode, we are receiving an error defined below,

SFApiRequestError: Maximum number of redirects exceeded

### Steps To Reproduce:

1.  Go to "Einstein for Developers" extension and click on "Ask"
2.  This throws an error saying "SFApiRequestError: Maximum number of redirects exceeded"

### Expected result
This should not throw an error.

### Actual result
This is throwing an error and obstructing the usage of functionality.

_Describe what actually happened instead_.

### Additional information: 
Have tried with latest version of VS code also but still error persists.

**Salesforce Einstein For Developers Version in VS Code**: v0.39.0

**VS Code version**: 1.86

**Comment by Salesforcetestuser** [comment] 2024-02-29 15:23
Tried updating the Vscode and CLI to latest versions and now the extension is in "Activating" stage forever.
![Annotation 2024-02-29 092417](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/161645102/f364f4a0-c1d9-4e29-b590-43e1a045690a)

**Comment by AnanyaJha** [comment] 2024-03-04 20:05
Hi @Salesforcetestuser , sorry you're seeing these issues. We'll have a member of our team investigate cc @randi274

**Comment by randi274** [comment] 2024-03-04 21:21
Confirmed and closing as duplicate of #49

**Closed by randi274** 2024-03-04 21:21 UTC
Labels: duplicate
