### ISSUE TITLE
SFApiRequestError: Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by debprotim** [forcedotcom/Einstein-GPT-for-Developers#60] opened 2024-03-27 20:39 UTC
Summary
While clicking on the "ask" tin the "Einstein for developers" extension in VScode, we are receiving an error defined below,

SFApiRequestError: Maximum number of redirects exceeded

Steps To Reproduce:
Go to "Einstein for Developers" extension and click on "Ask"
This throws an error saying "SFApiRequestError: Maximum number of redirects exceeded"
Expected result
This should not throw an error.

Actual result
This is throwing an error and obstructing the usage of functionality.

Describe what actually happened instead.

Additional information:
Have tried with latest version of VS code also but still error persists.

Salesforce Einstein For Developers Version in VS Code: v0.39.0

VS Code version: 1.86

**Comment by smarvez** [comment] 2024-03-29 18:14
Hi @debprotim, thanks for the info and for your patience as we try to resolve this issue for you! Can you let me know if you're getting this error for all Einstein for Developers features? I.e. - Can you use our inline autocomplete feature? Does the command "Einstein: Generate Code" return a completion if you're in an Apex file? I would assume you'd see the same error for these features as well but I just want to rule out something specific to the sidebar. Additionally, I noticed your Einstein for Developers extension version is a little out of date so if you could update to the latest that would be great.

**Comment by smarvez** [comment] 2024-03-29 19:53
Assuming you’re not able to get a response from any Einstein for Developers features, our suspicion is that the proxy you’re using is causing the redirects. By default our extension is setting the maximum number of redirects to 5. One way for us to test this would be to have you run a cURL command and see if the request shows up in our logs.

**Comment by debprotim** [comment] 2024-04-01 20:04
Yes, it is not working. Same error is popping up.

**Comment by RitamAgrawal** [comment] 2024-04-03 20:45
@debprotim I have increased the max_redirect limit and and would like to share the vsixes with you. GH doesn't support the VSIX to be shared here. What else would be a great way to connect with you? Also have you tried with latest version of Einstein For Developers v0.43.0 ?

**Comment by debprotim** [comment] 2024-04-05 20:49
I installed the vsix file. Anything particular you are looking for?

**Comment by RitamAgrawal** [comment] 2024-04-05 21:32
@debprotim Then re run the steps and let us know if you still see the error.

**Comment by debprotim** [comment] 2024-04-12 21:44
Same error:
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/8632083/3c973113-1d1b-445a-a6ff-e0883aa2c580)

**Comment by floralan** [comment] 2024-04-16 18:27
Hi @debprotim, given that the new VSIX file with a raised max-redirect limit didn't resolve the issue, it seems likely that the proxy settings on your end are causing an infinite redirect loop or an excessively high number of redirections. I have asked the support engineer to assist you in investigating the proxy settings on your machine. Please let us know if you have any questions or need further assistance with this.

**Comment by RitamAgrawal** [comment] 2024-04-23 20:58
@debprotim This seems like a one-off user settings issue. Let us know how else if we can help you, otherwise would like to close this issue. Thank you for raising your concerns.

**Comment by smarvez** [comment] 2024-04-29 17:00
Hi @debprotim - Closing this issue out since the root cause appears to be a proxy setting issue. Please feel free to re-open or create a new issue if you have further questions.

**Closed by smarvez** 2024-04-29 17:00 UTC
Labels: More Information Required, INVESTIGATION P3

**Comment by gbockus-sf** [comment] 2024-05-03 20:07
We had a follow up support meeting to help the user debug the proxy issue further and found the following: 
There was a http_proxy setting in vscode.  When removed the user was able to successfully hit the E4D endpoints for all features.
However without that setting the user was unable to auth against their orgs.  

We provided the following guidance: 
Work around: 
- Use CLI with proxy env vars set to do auth 
- Remove http_proxy setting from vscode
This allows the user to still auth as necessary but decouples the proxy from VSCode so both E4D and standard SFVSCE tools works as expected. 

Recommendations: 
User should reach out to their IT support and have them follow up on why their proxy is hitting max redirect with E4D generation endpoints: `https://api.salesforce.com/einstein/gpt/code/v1-alpha.1/`

Attempted to utilize curl to track the redirects taking place, but got the expected 404 from the command line
